version: "3.8"

services: 
  frontend:
    image: nginx:alpine
    hostname: frontend
    restart: 'unless-stopped'
    networks:
      - frontend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/app
    restart: 'unless-stopped'
    networks:
      - frontend
networks:
  frontend:
    external:
      name: custom-frontend