export const GET_ADMIN_REQUEST = 'GET_ADMIN_REQUEST';
export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';
export const GET_ADMIN_FAILURE = 'GET_ADMIN_FAILURE';

export const ADD_AVERAGE_PACE_BASELINE_REQUEST =
  'ADD_AVERAGE_PACE_BASELINE_REQUEST';
export const ADD_AVERAGE_PACE_BASELINE_SUCCESS =
  'ADD_AVERAGE_PACE_BASELINE_SUCCESS';
export const ADD_AVERAGE_PACE_BASELINE_FAILURE =
  'ADD_AVERAGE_PACE_BASELINE_FAILURE';

export const UPDATE_AVERAGE_PACE_BASELINE_REQUEST =
  'UPDATE_AVERAGE_PACE_BASELINE_REQUEST';
export const UPDATE_AVERAGE_PACE_BASELINE_SUCCESS =
  'UPDATE_AVERAGE_PACE_BASELINE_SUCCESS';
export const UPDATE_AVERAGE_PACE_BASELINE_FAILURE =
  'UPDATE_AVERAGE_PACE_BASELINE_FAILURE';

export const DELETE_AVERAGE_PACE_BASELINE_REQUEST =
  'DELETE_AVERAGE_PACE_BASELINE_REQUEST';
export const DELETE_AVERAGE_PACE_BASELINE_SUCCESS =
  'DELETE_AVERAGE_PACE_BASELINE_SUCCESS';
export const DELETE_AVERAGE_PACE_BASELINE_FAILURE =
  'DELETE_AVERAGE_PACE_BASELINE_FAILURE';

export const ADD_AVERAGE_PACE_LENGTH_REQUEST =
  'ADD_AVERAGE_PACE_LENGTH_REQUEST';
export const ADD_AVERAGE_PACE_LENGTH_SUCCESS =
  'ADD_AVERAGE_PACE_LENGTH_SUCCESS';
export const ADD_AVERAGE_PACE_LENGTH_FAILURE =
  'ADD_AVERAGE_PACE_LENGTH_FAILURE';

export const UPDATE_AVERAGE_PACE_LENGTH_REQUEST =
  'UPDATE_AVERAGE_PACE_LENGTH_REQUEST';
export const UPDATE_AVERAGE_PACE_LENGTH_SUCCESS =
  'UPDATE_AVERAGE_PACE_LENGTH_SUCCESS';
export const UPDATE_AVERAGE_PACE_LENGTH_FAILURE =
  'UPDATE_AVERAGE_PACE_LENGTH_FAILURE';
