export const GET_ANALYTIC_REQUEST = 'GET_ANALYTIC_REQUEST';
export const GET_ANALYTIC_SUCCESS = 'GET_ANALYTIC_SUCCESS';
export const GET_ANALYTIC_FAILURE = 'GET_ANALYTIC_FAILURE';

export const GET_ALL_BASELINE_REQUEST = 'GET_ALL_BASELINE_REQUEST';
export const GET_ALL_BASELINE_SUCCESS = 'GET_ALL_BASELINE_SUCCESS';
export const GET_ALL_BASELINE_FAILURE = 'GET_ALL_BASELINE_FAILURE';
