export const GET_ITEM_DETAIL_BASELINE_REQUEST =
  'GET_ITEM_DETAIL_BASELINE_REQUEST';
export const GET_ITEM_DETAIL_BASELINE_SUCCESS =
  'GET_ITEM_DETAIL_BASELINE_SUCCESS';
export const GET_ITEM_DETAIL_BASELINE_FAILURE =
  'GET_ITEM_DETAIL_BASELINE_FAILURE';

export const UPDATE_ITEM_DETAIL_BASELINE_REQUEST =
  'UPDATE_ITEM_DETAIL_BASELINE_REQUEST';
export const UPDATE_ITEM_DETAIL_BASELINE_SUCCESS =
  'UPDATE_ITEM_DETAIL_BASELINE_SUCCESS';
export const UPDATE_ITEM_DETAIL_BASELINE_FAILURE =
  'UPDATE_ITEM_DETAIL_BASELINE_FAILURE';
