export const OPEN_UPLOAD_MODAL = 'OPEN_UPLOAD_MODAL';
export const CLOSE_UPLOAD_MODAL = 'CLOSE_UPLOAD_MODAL';

export const OPEN_EDIT_MODAL = 'OPEN_EDIT_MODAL';
export const CLOSE_EDIT_MODAL = 'CLOSE_EDIT_MODAL';

export const OPEN_CONFIRM_MODAL = 'OPEN_CONFIRM_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';

export const OPEN_UPLOAD_SUCCESS_MODAL = 'OPEN_UPLOAD_SUCCESS_MODAL';
export const OPEN_UPLOAD_FAIL_MODAL = 'OPEN_UPLOAD_FAIL_MODAL';

export const OPEN_EDIT_SUCCESS_MODAL = 'OPEN_EDIT_SUCCESS_MODAL';
export const OPEN_EDIT_FAIL_MODAL = 'OPEN_EDIT_FAIL_MODAL';

export const OPEN_DELETE_SUCCESS_MODAL = 'OPEN_DELETE_SUCCESS_MODAL';
export const OPEN_DELETE_FAIL_MODAL = 'OPEN_DELETE_FAIL_MODAL';

export const OPEN_UPDATE_BASELINE_SUCCESS_MODAL =
  'OPEN_UPDATE_BASELINE_SUCCESS_MODAL';
export const CLOSE_UPDATE_BASELINE_SUCCESS_MODAL =
  'CLOSE_UPDATE_BASELINE_SUCCESS_MODAL';

export const OPEN_UPDATE_BASELINE_FAIL_MODAL =
  'OPEN_UPDATE_BASELINE_FAIL_MODAL';
export const CLOSE_UPDATE_BASELINE_FAIL_MODAL =
  'CLOSE_UPDATE_BASELINE_FAIL_MODAL';

export const OPEN_HELP_MODAL = 'OPEN_HELP_MODAL';
export const CLOSE_HELP_MODAL = 'CLOSE_HELP_MODAL';

export const CLOSE_SUCCESS_FAIL_MODAL = 'CLOSE_SUCCESS_FAIL_MODAL';
