export const GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE';

export const ADD_STOPWORD_SUCCESS = 'ADD_STOPWORD_SUCCESS';
export const ADD_STOPWORD_FAILURE = 'ADD_STOPWORD_FAILURE';

export const DELETE_STOPWORD_SUCCESS = 'DELETE_STOPWORD_SUCCESS';
export const DELETE_STOPWORD_FAILURE = 'DELETE_STOPWORD_FAILURE';

export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_FAILURE = 'ADD_TAG_FAILURE';

export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';
